import joblib
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI(title="REF: personality_dataset.csv - Prediction Service")

# Load preprocessor and personalitypredicting model generated by my notebook
preprocessor = joblib.load("preprocessor.pkl")
model = joblib.load("personality_model.pkl")

# Schema
class UserFeatures(BaseModel):
    Time_spent_Alone: float = Field(..., example=4.5)
    Stage_fear: str = Field(..., description="'Yes' or 'No'", example="Yes")
    Social_event_attendance: float = Field(..., example=3.0)
    Going_outside: float = Field(..., example=2.0)
    Drained_after_socializing: str = Field(..., description="'Yes' or 'No'", example="No")
    Friends_circle_size: float = Field(..., example=6.0)
    Post_frequency: float = Field(..., example=3.5)

@app.post("/predict")
def predict_personality(data: UserFeatures):
    try:
        #  Convert Pydantic payload into a 1-row Pandas DataFrame 
        input_df = pd.DataFrame([data.model_dump()]) 

        # Pass through the saved StandardScaler + OneHotEncoder
        processed_matrix = preprocessor.transform(input_df)

        #  Predict 
        prediction_int = model.predict(processed_matrix)[0]
        # convert class id to string
        verdict = "Extrovert" if prediction_int == 0 else "Introvert"

        return {
            "status": "success",
            "prediction": verdict,
            "raw_class_id": int(prediction_int)
        }

    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Inference Error: {str(e)}")

@app.get("/")
def health_check():
    return {"model_loaded": True, "preprocessor_loaded": True}